#! /bin/sh

# set root pointer
xsetroot -cursor_name left_ptr

~/.config/picom/launch_picom.sh &

~/.config/polybar/launch_polybar.sh &

pgrep -x sxhkd > /dev/null || sxhkd &

# Main monitor
bspc monitor HDMI-0 -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         1
bspc config window_gap           20 

bspc config split_ratio          0.52

bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config single_monocle       true

bspc config normal_border_color "#3b444b"
bspc config focused_border_color "#ebbcba"

bspc rule -a Spotify desktop=^10
